<a href="https://colab.research.google.com/github/PosgradoMNA/actividades-de-aprendizaje-A01793654/blob/main/Actividad3(IBM_Mod_5).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Actividad 3 (Curos de IBM modulo 5)

## Bernardo Mijangos Flores
### Matricula A01793654

## Laboratorio 5.1 matriz con numpy

In [6]:
# Tranfiera la siguiente lista a una matriz en numpy

import numpy as np
a=[1,2,3,4,5]

x = np.array(a)
x

array([1, 2, 3, 4, 5])

In [7]:
# encontrar el typo de x usando la funcion type()

type(x)

numpy.ndarray

In [8]:
# encontrar la forma de la matriz

x.shape

(5,)

In [9]:
# encontrar el tipo de dato de la matriz

x.dtype

dtype('int64')

In [10]:
# encontrar la media de la matriz

x.mean()

3.0

# 1D numpy en python

In [12]:
# crear la siguiente lista:

a = ["0", 1, "two", "3", 4]
a

['0', 1, 'two', '3', 4]

In [13]:
# podemos acceder a cada elemento usando un corchete de la siguiente manera:

print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: two
a[3]: 3
a[4]: 4


In [14]:
# importando la libreria de numpy

import numpy as np

In [15]:
# se crea una matriz en numpy

a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [17]:
# cada elemento es del mismo tipo, en este caso enteros

# se muestra cada elemento de la matriz

print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: 2
a[3]: 3
a[4]: 4


In [18]:
# comprobando la version de numpy

print(np.__version__)

1.21.6


In [19]:
# comprobando el tipo de la matriz

type(a)

numpy.ndarray

In [20]:
# Como las matrices numpy contienen datos del mismo tipo, podemos usar el atributo "dtype" para obtener el tipo de datos de los elementos de la matriz. En este caso, es un entero de 64 bits:

# comprobando los tipos de valores

a.dtype

dtype('int64')

In [22]:
# Verificar el tipo de matriz y el tipo de valor

b = np.array([3.1, 11.02, 6.2, 213.2, 5.2])

type(b)

numpy.ndarray

In [23]:
# Verificar el tipo de valor de la matriz

b.dtype

dtype('float64')

In [24]:
# considerar la matriz c:

c = np.array([20, 1, 2, 3, 4])
c

array([20,  1,  2,  3,  4])

In [25]:
# asignar 100 al primer elemento

c[0] = 100
c

array([100,   1,   2,   3,   4])

In [26]:
# Asignar 0 al quinto elemento

c[4] = 0
c

array([100,   1,   2,   3,   0])

In [27]:
# asignar 20 al segundo elemento de la siguiente matriz:

a = np.array([10, 2, 30, 40,50])
a

array([10,  2, 30, 40, 50])

In [28]:
a[1] = 20
a

array([10, 20, 30, 40, 50])

## Slicing

In [29]:
# Slicing en la matriz de numpy

d = c[1:4]
d

array([1, 2, 3])

In [30]:
# establecer el cuarto y quinto elemento los valores de 300 y 400

c[3:5] = 300, 400
c

array([100,   1,   2, 300, 400])

In [31]:
# También podemos definir los pasos en el corte, así: [start:end:step].

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [32]:
# Si no pasamos start se considera 0

print(arr[:4])

[1 2 3 4]


In [33]:
# Si no pasamos end, considera hasta la longitud de la matriz.

print(arr[4:])

[5 6 7]


In [34]:
# Si no pasamos el paso se considera 1

print(arr[1:5:])

[2 3 4 5]


In [36]:
# Imprime los elementos pares en la matriz

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr[1:8:2])

[2 4 6 8]


## Asignar valores a una lista

In [40]:
# crea la lista de indices

select = [0, 2, 3, 4]
select

[0, 2, 3, 4]

In [41]:
# Usa la lista para seleccionar elementos

d = c[select]
d

array([100000, 100000, 100000, 100000])

In [42]:
# asigna los elementos especificos a un nuevo valor

c[select] = 100000
c

array([100000,      1, 100000, 100000, 100000])

## Otros atributos

In [43]:
# crea una matriz en numpy

a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [44]:
# obtiene el tamaño de la matriz

a.size

5

In [45]:
# obtiene el numero de dimensiones de la matriz

a.ndim

1

In [46]:
# obtiene la forma/tamaño de la matriz

a.shape

(5,)

In [47]:
# Encuentre el tamaño, la dimensión y la forma de la matriz b

b = np.array([10, 20, 30, 40, 50, 60, 70])

In [49]:
b.size

7

In [50]:
b.ndim

1

In [51]:
b.shape

(7,)